# Generated by Django 5.2.10 on 2026-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0772_clean_up_imageattachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="mandatory_topics",
            field=models.BooleanField(default=False),
        ),
    ]
